development:
  adapter: postgresql
  host: localhost
  database: dan
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  database: dan
  encoding: UTF8

production:
  adapter: postgresql
  database: dan
  encoding: UTF8
